///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UsersModelJsonData {
/*
{
  "name": "Unsplash_001",
  "author": "Unsplash",
  "url": "https://raw.githubusercontent.com/anticor248/Json-Cloud-Wallpaper-Base/main/wallpapers_pack/unsplash_wallpapers_001.png",
  "thumbUrl": "https://raw.githubusercontent.com/anticor248/Json-Cloud-Wallpaper-Base/main/wallpapers_pack/unsplash_wallpapers_001_thumb.png"
}
*/

  String? name;
  String? author;
  String? url;
  String? thumbUrl;

  UsersModelJsonData({
    this.name,
    this.author,
    this.url,
    this.thumbUrl,
  });
  UsersModelJsonData.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    author = json['author']?.toString();
    url = json['url']?.toString();
    thumbUrl = json['thumbUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['author'] = author;
    data['url'] = url;
    data['thumbUrl'] = thumbUrl;
    return data;
  }
}

class UsersModelJson {
/*
{
  "data": [
    {
      "name": "Unsplash_001",
      "author": "Unsplash",
      "url": "https://raw.githubusercontent.com/anticor248/Json-Cloud-Wallpaper-Base/main/wallpapers_pack/unsplash_wallpapers_001.png",
      "thumbUrl": "https://raw.githubusercontent.com/anticor248/Json-Cloud-Wallpaper-Base/main/wallpapers_pack/unsplash_wallpapers_001_thumb.png"
    }
  ]
}
*/

  List<UsersModelJsonData?>? data;

  UsersModelJson({
    this.data,
  });
  UsersModelJson.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <UsersModelJsonData>[];
      v.forEach((v) {
        arr0.add(UsersModelJsonData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
